### ISSUE TITLE
Do the work

### ISSUE THREAD

**Issue by martinmoene** [martinmoene/string-view-lite#1]
... quoting [Kate Gregory, Cpp2017](https://youtu.be/ARosL9xrozk?t=10m18s).

- [x] Create initial code files string_view.hpp end test files and compilation command.
- [x] Create class template `basic_string_view` with method declarations.
- [x] Implement constructors
- [x] Implement assignment
- [x] Implement iterators
- [x] Implement element access
- [x] Implement capacity
- [x] Implement modifiers
- [x] Implement operations
- [x] Implement string conversion operations, class methods (optional extension)
- [x] Implement string conversion operations, free functions (optional extension)
- [x] Implement comparisons, primary
- [x] Implement comparisons, extended
- [x] Implement streaming
- [x] Implement "sv" literals
- [x] Implement std::hash<>
- [x] Setup Travis
- [x] Setup AppVeyor
- [x] Setup 'on Wandbox'
- [x] Setup 'on Godbolt'
- [x] Create Readme
- [x] Fine-tune Readme
- [x] Release 0.2.0
- [x] Setup 'on conan' (@agauniyal ?)
- [x] Update Readme

[![Build Status](https://travis-ci.org/martinmoene/string-view-lite.svg?branch=master)](https://travis-ci.org/martinmoene/string-view-lite) [![Build status](https://ci.appveyor.com/api/projects/status/502879rbo0rrikrs/branch/master?svg=true)](https://ci.appveyor.com/project/martinmoene/string-view-lite/branch/master)

*Interface and implementation*
- [string_view on cppreference](http://en.cppreference.com/w/cpp/string/basic_string_view).
- [n4659 - C++17 Working Draft: string_view](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/n4659.pdf#page=780).
- [Implementation by Marshall Clow](https://github.com/mclow/string_view).
- [libc++: string_view](https://llvm.org/svn/llvm-project/libcxx/trunk/include/string_view).

*Other implementations on GitHub*
- Google's [Abseil string_view](https://github.com/abseil/abseil-cpp/tree/master/absl/strings) (non-template).
- @thelink2012, Denilson das Mercês Amorim's [standalone version of libc++'s string_view](https://github.com/thelink2012/libcxx_string_view).
- @bitwizeshift, Matthew Rodusek's [string_view Standalone](https://github.com/bitwizeshift/string_view-standalone)
- @satoren 's [string_view for C++03 C++11 C++14](https://github.com/satoren/string_view).
- @simber, Simon Simber's [C++ string_view extension library.](https://github.com/simber/string_view-building-blocks).
- [Search _string view c++_ on GitHub](https://github.com/search?l=C%2B%2B&q=string+view+c%2B%2B&type=Repositories&utf8=%E2%9C%93).

*Presentations*
- Marshall Clow. [string_view - when to use it, and when not](https://cppcon2015.sched.com/event/3vch/stringview-when-to-use-it-and-when-not?iframe=yes&w=700&sidebar=yes&bg=no#). CppCon 2015. [video](https://youtu.be/H9gAaNRoon4), [slides](https://github.com/CppCon/CppCon2015/blob/master/Presentations/string_view/string_view%20-%20Marshall%20Clow%20-%20CppCon%202015.pdf).
- Neil MacIntosh. [A few good types: Evolving array_view and string_view for safe C++ code](https://cppcon2015.sched.com/event/3vbQ/a-few-good-types-evolving-arrayview-and-stringview-for-safe-c-code). CppCon 2015. [video](https://youtu.be/C4Z3c4Sv52U), [slides](https://github.com/CppCon/CppCon2015/blob/master/Presentations/A%20Few%20Good%20Types/A%20Few%20Good%20Types%20-%20Neil%20MacIntosh%20-%20CppCon%202015.pdf).

*Proposals*
- Jeffrey Yasskin. [n3334 - Proposing array_ref<T> and string_ref](https://wg21.link/n3334). 2012.
- Jeffrey Yasskin. [n3921 - string_view: a non-owning reference to a string, revision 7](http://wg21.link/n3921). **Adopted 2014-02**.
- Alisdair Meredith. [n4288 - Strike string_view::clear from Library Fundamentals](http://wg21.link/n4288). **Adopted 2014-11**.
- Neil MacIntosh. [p0123 - Unifying the interfaces of string_view and array_view](http://wg21.link/p0123). 2015.
- Beman Dawes, Alisdair Meredith. [p0220 - Adopt Library Fundamentals V1 TS Components for C++17 (R1)](https://wg21.link/p0220r1). 2016.
- Marshall Clow. [p0254 - Integrating std::string_view and std::string](http://wg21.link/p0254). **Adopted 2016-06**.
- Nicolai Josuttis. [p0392 - Adapting string_view by filesystem paths](https://wg21.link/p0392r0). 2016.
- Marshall Clow. [p0403 - Literal suffixes for basic_string_view](http://wg21.link/p0403). 2016.
- Peter Sommerlad. [p0506 - use string_view for library function parameters instead of const string &/const char *](http://wg21.link/p0506). 2017.
- Daniel Krugler. [wg2946 - LWG 2758's resolution missed further corrections](https://wg21.link/lwg2946). 2017.

**Comment by agauniyal** [comment]
Just mention me in the comments once you think its time to publish on conan 👍

**Comment by martinmoene** [comment]
Thanks, I'll do.

**Comment by martinmoene** [comment]
Hi @agauniyal , just released *string-view lite* 0.2.0.
Once you've published it on Conan, I'll update the Readme.
Thanks a lot!

**Comment by agauniyal** [comment]
@martinmoene its done 🎉 
https://github.com/agauniyal/conan-string-view-lite

**Comment by martinmoene** [comment]
Thanks!
