### ISSUE TITLE
User defined literals must begin with _

### ISSUE THREAD

**Issue by LegalizeAdulthood** [martinmoene/string-view-lite#2]
User-defined literals that don't begin with `_` are reserved for the standard.

**Comment by martinmoene** [comment]
Yes, I know, but I'd like to stand in for the standard in the absence of `std::string_view`.

Likely there's a mechanism in clang that prevents me in doing that.

**Comment by martinmoene** [comment]
I've added [configuration macros](https://github.com/martinmoene/string-view-lite#add-or-omit-literal-operators-sv-and-_sv) to add literal operator `sv` (default not present) and to omit literal operator `_sv` (default present).
