### ISSUE TITLE
Literal string constructors should be marked noexcept

### ISSUE THREAD

**Issue by xirius** [martinmoene/string-view-lite#22]
If you declare a string constant in the global space you might see clang-tidy showing the warning that "Initialization of X with static storage duration may throw an exception that cannot be caught".
Actually initialization of the constant literal string never throws an exception.

Example:
```C++
const char* path = "file:///path/to/file.ext";
```

To fix it the following constructors should be marked `noexcept`:
```C++
nssv_constexpr basic_string_view( CharT const * s, size_type count ) nssv_noexcept

nssv_constexpr basic_string_view( CharT const * s) nssv_noexcept
```
By the way `Traits::length(s)` is marked `constexpr` starting from C++17. So the following constructor can only be marked `constexpr` for C++17+.
```C++
nssv_constexpr basic_string_view( CharT const * s)
    : data_( s )
    , size_( Traits::length(s) )
{}
```

**Comment by martinmoene** [comment]
See code sample at bottom.

The clang-tidy warning *exception cannot be caught* does occur with "string_view lite* but not with the compiler-provided `string_view` (MSVC's in my case).

As far as I can see, the C++ standard does not differentiate between `constexpr` and non-`constexpr` arguments...

*string_view lite* can be used with C++98 upto and including the latest version. While perhaps not needed with C++17 and later, enabling so *may* ease migrating from pre-C++17 to C++17 or later.

With pre-C++17, the traits-using constructor will not be `constexpr` (but still may be tagged so), with C++17 and later that constructor *will* be `constexpr`.

---

```
#include "nonstd/string_view.hpp"

constexpr char const * path = "file:///path/to/file.ext";

constexpr nonstd::string_view sv(path);

int main()
{
    const nonstd::string_view svl(path);
}

// clang-tidy -checks=* issue.cpp -extra-arg=-std=c++17 -extra-arg=-I../../../include/ -extra-arg=-Dnssv_CONFIG_SELECT_STRING_VIEW=nssv_STRING_VIEW_NONST
```

Output:

```
...
.../issue.cpp:7:31: warning: initialization of 'sv' with static storage duration may throw an exception that cannot be caught [cert-err58-cpp]
constexpr nonstd::string_view sv(path);
                              ^
.../nonstd/string_view.hpp:463:20: note: possibly throwing constructor declared here
    nssv_constexpr basic_string_view( CharT const * s)
...
```

**Comment by martinmoene** [comment]
Concern @xirius : what if it concerns a large non-`constexpr` string consuming the stack?

**Comment by martinmoene** [comment]
Concern @xirius : what if it concerns a large non-constexpr string consuming the stack?

**Comment by xirius** [comment]
For the pre-C++17, maybe it is possible to use something like that ?

```c++
constexpr size_t length(const char* value, size_t len = 0)
{
    return *value != '\0' ? length(value + 1, len + 1) : len;
}

nssv_constexpr basic_string_view( CharT const * s) nssv_noexcept // non-standard noexcept
    : data_( s )
    , size_(length(s) )
{}
```

**Comment by xirius** [comment]
C++14 supports `constexpr` loops. Not sure if it adds any value though. As you mentioned modern compilers should optimize it to something similar anyway.

```c++
constexpr size_t length2(const char* value) {
    for (size_t i = 0;; i++)
        if (value[i] == '\0')
            return i;
}
```
Thanks for the quick fixes ;)

**Comment by martinmoene** [comment]
Thinking the concerns are addressed, closing this issue.
