### ISSUE TITLE
test on linux

### ISSUE THREAD

**Issue by xor2003** [martinmoene/string-view-lite#23]
Sorry not clear how to test on Linux.
Instructions provided are for Windows.

**Comment by martinmoene** [comment]
Paraphrasing the 'Windows instructions' or looking at [.travis.yml](https://github.com/martinmoene/string-view-lite/blob/f3bf44f32045cad88083fa49a6b23ee2204b7845/.travis.yml#L158), and assuming *string-view lite* sources are in in `~/string-view-lite`:

```
mkdir ~/build-string_view-lite && cd ~/build-string_view-lite
cmake -G "Unix Makefiles" -DSTRINGVIEW_LITE_OPT_SELECT_NONSTD=ON -DSTRINGVIEW_LITE_OPT_BUILD_TESTS=ON -DSTRINGVIEW_LITE_OPT_BUILD_EXAMPLES=OFF ~/string-view-lite
cmake --build .
ctest --output-on-failure
```

**Comment by xor2003** [comment]
Thank you. It works on RHEL 6 gcc 6.
But fails on gcc 4.4 - but no problem.

**Comment by martinmoene** [comment]
The lowest version of gcc that is tested via [Travis is gcc 4.8](https://travis-ci.org/martinmoene/string-view-lite/jobs/517446242); that one succeeds.
