### ISSUE TITLE
CMake Release?

### ISSUE THREAD

**Issue by AndrewGaspar** [martinmoene/string-view-lite#26]
Hey, big fan! Currently I'm using optional-lite, span-lite, and string-view-lite. I noticed you recently updated optional and span to support a CMake's find_package feature. It would be incredibly useful for me if you also updated string-view-lite, since it lets me throw out my hand-rolled find_package for these libraries.

No worries if this isn't a high priority!

**Comment by martinmoene** [comment]
Getting [there](https://github.com/martinmoene/nonstd-lite-project/issues/23), albeit slowly.

**Comment by AndrewGaspar** [comment]
Sounds good! Thank you for providing these libraries!

**Comment by AndrewGaspar** [comment]
Looks like this issue is resolved! Thanks!
