### ISSUE TITLE
-Wshadow fails

### ISSUE THREAD

**Issue by mattyclarkson** [martinmoene/string-view-lite#31]
It would be good if the header was compatible with `-Wshadow`. It has [one error](https://github.com/martinmoene/string-view-lite/blob/52c8f40ffae21dcf88aa2a38111b0d6c18e5a1fe/include/nonstd/string_view.hpp#L877):

```        nssv_constexpr explicit not_in_view( basic_string_view v ) : v( v ) {}```
```string_view.hpp:858:68: warning: declaration of ‘v’ shadows a member of ‘nonstd::sv_lite::basic_string_view<CharT, Traits>::not_in_view’ [-Wshadow]```

The local argument just needs to be changed:

```        nssv_constexpr explicit not_in_view( basic_string_view view ) : v( view ) {}```

**Comment by martinmoene** [comment]
Thanks @mattyclarkson , took care of it.

**Comment by mattyclarkson** [comment]
Awesome, thanks! Is there a change of a `1.3.1` release for the fix?

**Comment by martinmoene** [comment]
I'll make a release, likely 1.4.0 and hopefully today.

**Comment by martinmoene** [comment]
@mattyclarkson , [v1.4.0 has been released](https://github.com/martinmoene/string-view-lite/releases/tag/v1.4.0).
