### ISSUE TITLE
Error with incomplete type when compiling using NEC compiler

### ISSUE THREAD

**Issue by acmnpv** [martinmoene/string-view-lite#32]
Hello,

we are using string_view_lite to support the functionality in the GROMACS project (https://gitlab.com/gromacs/gromacs) for the current release before we are making the actual switch to C++17 and native support.

We recently got a report (https://gitlab.com/gromacs/gromacs/-/issues/3533) that the compilation of our code fails in the string_view compatibility layer with the following error when using the NEC compiler

    "/gromacs-2020.1/src/gromacs/compat/string_view.h", line 894: error: incomplete type is not allowed
    const basic_string_view v;

Are you aware of other compilers having similar issues?

Thanks for the help!

**Comment by martinmoene** [comment]
Hi Paul (@acmnpv ),

I see you are [currently using string_view_lite v1.1 in GROMACS v2020.1](https://gitlab.com/gromacs/gromacs/-/blob/v2020.1/src/gromacs/compat/string_view.h), whereas the [latest release of string_view_lite is 1.4](https://github.com/martinmoene/string-view-lite/releases/tag/v1.4.0).

I think it's best to see how the latest release fares.

**Comment by acmnpv** [comment]
Hello, I prepared a MR to the latest version (https://gitlab.com/gromacs/gromacs/-/merge_requests/207) and we asked the user to try with this, but the problem persists (https://gromacs.bioexcel.eu/t/gromacs-installation-error/115/3). The user reports this might be a compiler error, so this can be closed if there are no obvious fixes.

**Comment by martinmoene** [comment]
Thanks Paul (@acmnpv),

Trying things out with the NEC compiler is not something I can investigate myself, so I cannot be of help here unfortunately.

**Comment by quickwritereader** [comment]
recently I faced the same error.
in my case it was because of `-std=c++11`. 
and I am able to avoid it using `-std=gnu++11` instead

**Comment by martinmoene** [comment]
@quickwritereader Thanks for your report.
