### ISSUE TITLE
Conan package

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [martinmoene/string-view-lite#4]
Hello,
Do you know about [Conan](https://github.com/conan-io/conan)?
[Conan](http://docs.conan.io/en/latest/) is modern dependency manager for C++. And will be great if your library will be available via package manager for other developers.

[Here](https://github.com/bincrafters/conan-templates) you can find example, how you can create package for the library. 

If you have any questions, just ask :-)

**Comment by martinmoene** [comment]
Hi @ZaMaZaN4iK ,

I do know about Conan, see e.g. [section installation of string-view lite](https://github.com/martinmoene/string-view-lite#installation).

I'v added (imported via Bintray web page) most of what may be of interest now and will have a look later if I could do better.

Thanks & cheers,
Martin

**Comment by martinmoene** [comment]
Conan support has been added in c877c2bb215e5800ea318edcd75f6b8f8d078de6
