### ISSUE TITLE
Wrong check for stream vs sentry

### ISSUE THREAD

**Issue by mprather** [martinmoene/string-view-lite#46]
In the write_to_stream method, the check on line 1384 is testing the stream.

```
    if ( !os )
        return os;
```

Should this check test the sentry instead?

```
  if (!sentry) {
    return os;
  }
```

**Comment by martinmoene** [comment]
Thanks a lot for your sharp observation !

Curious if you did find it by reading the code or due to the occurrence of an issue?

**Comment by mprather** [comment]
It was a code read-through.

**Comment by martinmoene** [comment]
Thank you.
