### ISSUE TITLE
Prevent construction/conversion from nullptr

### ISSUE THREAD

**Issue by mbs-c** [martinmoene/string-view-lite#47]
When introducing `string_view` into an old codebase, it is quite easy to accidentally leave nonsensical assignments from or comparisons to `nullptr` in your code. Adding a deleted constructor as follows allows developers to easily identify the offending assignments and comparisons:

```cpp

#if nssv_CPP11_OR_GREATER
    nssv_constexpr basic_string_view( std::nullptr_t ) nssv_noexcept = delete;
#endif
```

C++23 will also disallow constructing `std::basic_string_view` from `nullptr`: https://github.com/cplusplus/papers/issues/887

**Comment by martinmoene** [comment]
Ah, thank you for the pointer Moritz @mbs-c, I wasn't yet aware of this.

I'll add the proposed constructor.

**Comment by martinmoene** [comment]
In release [1.7.0](https://github.com/martinmoene/string-view-lite/releases/tag/v1.7.0).
