### ISSUE TITLE
Another release please...

### ISSUE THREAD

**Issue by eyalroz** [martinmoene/string-view-lite#52]
The last release was made almost 2 years ago, and 36 commits ago. Perhaps it's time for another one?

**Comment by martinmoene** [comment]
Good you ask :)

Will try to do that tomorrow.

**Comment by eyalroz** [comment]
Oh, and, by the way - perhaps you should get the [fmt](https://github.com/fmtlib/fmt) author(s) to use this class internally for the case when they can't use the standard library's. I just noticed that the version of fmt bundled within spdlog uses a somewhat broken string view.

**Comment by martinmoene** [comment]
Can you give a hint as to what to look for that is broken in _fmt_'s `string_view`?
I'm inclined to see how it does with my tests for _string_view lite_.

**Comment by martinmoene** [comment]
Published [Release 1.7.0](https://github.com/martinmoene/string-view-lite/releases/tag/v1.7.0).

Hope to update [_string_view lite_ on Conan](https://conan.io/center/string-view-lite) later today.

**Comment by eyalroz** [comment]
> Can you give a hint as to what to look for that is broken in fmt's string_view?

IIRC - no `empty()` method, no default ctor. But I might be wrong, plus like I said I might be talking about an adapted older version of fmt.

**Comment by martinmoene** [comment]
@eyalroz, indeed, _fmt_'s `string_view` lacks `empty()`, however it does have a default constructor (now).

**Comment by eyalroz** [comment]
... and that's why I thought you might want to pitch your string_view to them. They could remove some code they currently need to maintain themselves in favor of maybe a sub-repo (or just vendoring of one of your releases), and you would get... more visibility and magical glory I guess?

**Comment by martinmoene** [comment]
There're delicate balances to be struck between one's presences :)
